server:
  port: 8060

spring:
  application:
    name: configZuul
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sjiskevin/spring-cloud
          search-paths: config/zuul
          username: 
          password:
          default-label: master #配置文件分支
