server:
  port: 8090
#  servlet:
#    context-path: /product-server/

spring:
  application:
    name: product-server

eureka:
  client:
    service-url:
      defaultZone:  http://127.0.0.1:8080/eureka
